from tkinter import Tk
from tkinter.filedialog import askdirectory, askopenfilename
import os.path
from site_user_import import *

print(
'''Viedoc site and user import application.\n
This application imports study sites and users from Excel into Viedoc using the Web API.
In order to use this application, set up a Web API in Viedoc Admin with status Production and the appropriate scopes.\n
The Excel files must follow a defined structure. Please use the templates generated by this application.
''')

input("Press Enter to continue.")

# Create the root for the dialog window (folder/file selections)
root = Tk()
root.attributes("-topmost", True)
root.withdraw()

# Get output location
print("Select the folder where outputs should be saved. Note: Existing files may get overwritten!\n")
path = askdirectory(title = 'Select folder for saving output', parent = root) + "/"

# Create Excel template files if they do not exist yet
if path != "/":  # Output folder must have been selected
    try:  # Writing the Excel files within try statement, as permission may be denied.
        create_site_import_template(path)
        create_user_import_template(path)
    except:  # If writing the files did not work
        print("Permission denied. Do you have write access to the selected folder?\n")
        path = "/" #Remove selected path so that subsequent code won't run

# Get server to connect to
if path != "/":  # Output folder must have been selected
    endpoint_options = get_available_endpoint_options()
    option_numbers = [str(index) for index in range(1, len(endpoint_options) + 1)]
    server_choice = "0"
    while server_choice not in option_numbers:
        print("Which region and environment should be used?")
        for index, option in enumerate(endpoint_options, start = 1):
            region, environment, resolved = option
            print(f" {index}: {region.title()} - {environment.title()} ({resolved.web_api})")
        server_choice = input("Choose one of the above options: ").strip()

    region, environment, resolved = endpoint_options[int(server_choice) - 1]
    print("\nPress Enter to use the YAML defaults, or provide URL overrides from Viedoc Admin.")
    api_override = input(f"API URL [{resolved.web_api}]: ").strip()
    token_override = input(f"Token URL [{resolved.sts}]: ").strip()
    sts, api = get_server(region, environment, api_override, token_override)

    # Get the client credentials interactively
    print("\nProvide the Client ID and Client secret obtained from Viedoc Admin - API configuration:")
    client_id = ""
    while len(client_id) != 36:
        client_id = input("Client ID: ").strip()
    
    client_secret = ""
    while len(client_secret) != 43:
        client_secret = input("Client secret: ").strip()
    
    # Write the first log entry in a try statement, as access might be denied
    try:
        writelog("Obtaining token from " + sts, path, option = "firstentry")
        writelog("- Client ID: " + client_id, path, disp = False, option = "notimestamp")
        writelog("- Client secret: " + client_secret[:3] + "*" * 37 + client_secret[-3:], path, disp = False, option = "notimestamp")
        
        # Get the token
        token = get_token(sts, path, client_id, client_secret)
        
    except:
        print("Unable to save a log file to the selected output folder. Select a folder where you have write permission.")
        token = ""  # If writing to log failed, save an empty token, so further code won't run.
else: token = ""

# Await user input and call respective functions
userInput = None
while(userInput != "0" and token != ""):  # Allow user input if a token exists and until 0 is entered
    print("Please select what you want to do:\n1: Get an Excel export with all study sites\n2: Get an Excel export with all study users")
    print("3: Create sites from Excel file\n4: Create users from Excel file\n0: End this program")
    userInput = input("Choose one of the above options: ")
    print("")
    if(userInput == "1"):
        writelog("User input: 1: Get an Excel export with all study sites.", path)
        get_sites(token, api, path)
    elif(userInput == "2"):
        writelog("User input: 2: Get an Excel export with all study users.", path)
        get_users(token, api, path)
    elif(userInput== "3"):
        writelog("User input: 3: Create sites from Excel file.", path)
        # Select the Excel file in a dialog window
        print("Select the Excel file containing the site details to import.")
        excelfile = askopenfilename(title = "Select the Excel file to import", parent = root)
        writelog("Selected Excel: " + excelfile, path)
        create_sites(token, api, path, excelfile)
    elif(userInput== "4"):
        writelog("User input: 4: Create users from Excel file.", path)
        # Select the Excel file in a dialog window
        print("Select the Excel file containing the user details to import.")
        excelfile = askopenfilename(title = "Select the Excel file to import", parent = root)
        writelog("Selected Excel: " + excelfile, path)
        create_users(token, api, path, excelfile)
    elif(userInput == "0"): print("")
    else: print("Not a valid option.\n")
try:
    writelog("Program ended.", path, disp = False)
    input("Program ended. A log is available at " + path + "log.txt")
except:
    input("Program ended because no valid output folder was selected.")
